name: BLEamit
description: An app that reacts to BLE broadcasts by changing screen color.
publish_to: "none"
version: 1.0.1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.35.5
  flutter_launcher_icons: ^0.14.4
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

